### ISSUE TITLE
Channel stats not updating before pressing a button

### ISSUE THREAD

**Issue by RandomUserGem** [claudiobernasconi/streamdeck-youtube#11]
Hello! Please, add ability to choose refresh time - like, every 60 seconds, every 10 minutes, etc. Right now, to update stats, you have to press a button. 
Also, it would be cool, if you add ability to login or at least open a webpage for this channel after pressing a button.

**Comment by claudiobernasconi** [comment]
Thank you for your feedback.

I decided to not add an automated refresh feature because the YouTube API limits the daily number of requests your can send. I also think that a button press is enough for this plugin. So there is a technical reason for the current behavior and I do not think I'm going to change it.

If you want to open the channel in the browser, I suggest using a different plugin like the one opening a website at a given URL. In this plugin, when you press the button it refreshes the data on the display so you cannot have two different actions with the same trigger.

I hope you understand, I wish you a great day.
